### ISSUE TITLE
pybikes support

### ISSUE THREAD

**Issue by homtec** [ubahnverleih/WoBike#15]
Nice repo 👍  - are you planning to add the providers to https://github.com/eskerda/pybikes ? They would be accessible via the citybik.es API then.

**Comment by PierrickP** [comment]
Thanks you.
This repo is more a documentation / reverse api.

We focus on the new kind of bike sharing (without bases, and often not supported by cities) like Ofo, gobee, mobike.
System supported by cities come often with open data (eg: Velib / velov in Paris / lyon  by JC Decaux)
Of course, pybikes' contributeurs can use this repo to add new providers ! 

On my side, i mapped somes on https://github.com/PierrickP/multicycles

**Comment by ubahnverleih** [comment]
The most of the APIs are revere engineered and in the last weeks we realised that some of the APIs are constantly changing. I'm not sure how we deal with this and how pybikes would do.
I think we also should add some hint for the sharing companies to the readme, showing them that it would be a benefit for all if they open their APIs. I think some of them are aware of this repo.

**Comment by PierrickP** [comment]
@ubahnverleih i spoke with getapony's CEO, he don't see the benefit of my app.
I tried to call gobee and ofo (+ French head of Marketing) on twitter if they have open API to report broken bikes, without success.

**Comment by ubahnverleih** [comment]
@PierrickP All the providers claim to revolutionize transportation, fixing the last mile problem and being so smart and innovative but don't want to be integrated in smart solutions which provide easy multimodal solutions in combination with public transport data and so on...
I think they are a bit feared that their competitor could benefit from the data.
But thank you so much for your effort!

**Comment by dschep** [comment]
Yeah, most of the Washington, DC providers(ofo, spin, limebike, mobike) have been completely unresponsive to me on both twitter and their support emails. JUMP on the other hand _gets it_. They already have public & documented APIs, respond on twitter, and I even met two folks from JUMP at a "BikeHackNight" meetup! on my side I made https://github.com/dschep/dc-bike-finder which I'm actually gonna present at the same meetup in February.

With respect to PyBikes, does their infrastructure/codebase support dockeless systems? Last I checked they wouldn't fit with the current model very cleanly. But, if so, I'll probably contribute a few systems to their code base since python & bikes are my favorite things :grinning:

**Comment by homtec** [comment]
@dschep I'm sure they would be happy to get a PR with support for dockless systems. :-)

**Comment by kael** [comment]
Regarding potential smart integration of this repository, how about publishing API documentation using the [Blueprint API language](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md) ?

Blueprint is a  _"documentation-oriented web API description language"_ in flavoured-markdown format that allows to describe API methods in a human and machine-readable format. The blueprint doc can then be converted into a [Swagger format](https://github.com/kminami/apib2swagger) and hence easily "universally" consumable.

There could be one page per service and a main page pointing to each service documentation.
