### ISSUE TITLE
Can Lime bike data be used for academic purposes?

### ISSUE THREAD

**Issue by luyuliu** [ubahnverleih/WoBike#99]
Can we collect lime bike data and use it for academic purposes? I notice this in the agreement:

Subject to Your strict compliance with this Agreement and the Additional Terms, Lime grants You a limited, revocable, non-exclusive, non-assignable, non-transferable license to _**download (temporary storage only)**_, display, view, use, play, and/or print one copy of the Content (excluding source and object code in raw form or otherwise, other than as made available to access and use to enable display and functionality) on a personal computer, mobile phone or other wireless Device, or other Internet enabled Device (each, a “Device”) for **_Your personal, non-commercial use only_**. 

This license does not include any resale or commercial use of the Services or its contents; **_any collection and use of any product listings, descriptions, or prices_**; any derivative use of the Services or their contents; any downloading or copying of account information for the benefit of another merchant; or _**any use of data mining, robots, or similar data gathering and extraction tools**_.

**Comment by robbi5** [comment]
¯\\\_(ツ)_/¯ 

**IANAL**, but if you have never installed the app, or never seen the Terms of Use - the API itself doesn't display terms of use - what should happen? 
I personally know multiple academic and "just for fun" projects that are scraping bike and scooter data and doing analysis and other interesting stuff with it. Because position data of rentable bikes & scooters is not personal user data, there really should be no problem to use the data.

Even more so, this whole repository only exists because the providers didn't fully understand yet that Open Data in the Mobility Sector benefits the whole society. So, in my opinion: Feel free to use it, have fun and do interesting and creative research with it - and talk about it, share your research and help to create better mobility for all of us :)
